#!/bin/bash

set -ex

cmd="${1:-hkam}"
dst="${2:-o}"

ssh $dst sudo systemctl stop $cmd
GOARCH=arm GOOS=linux go build -o ./out/ ./cmd/$cmd && scp ./out/$cmd $dst:bin/
ssh $dst sudo systemctl start $cmd
